<?php

namespace Database\Seeders;

use App\Models\MenuItem;
use Illuminate\Database\Seeder;

class MenuItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = \Faker\Factory::create();
        $breakfasts = [
            "pancakes", 
            "waffles", 
            "omelette", 
            'quiche', 
            'scramble', 
            "Apple dumplings",
            "Bacon, egg and cheese sandwich",
            "Banana Bread",
            "Lox Plate",
            "bagel with cream cheese",
            "biscuits and gravy",
            "breakfast cereal",
            "breakfast taco",
            "chicken and waffles",
            "chillaquiles",
            "Croissant",
            "dim sum",
            "Eggs Benedict",
            "shrimp and grits",
            "hash",
            "Huevos rancheros",
            "Idli",
            "Muesli",
            "oatmeal",
            "pork roll",
            "Youtiao",
            "Throdkin",
            "Tamago kake gohan"
        ];
        for($i = 0; $i<count($breakfasts);$i++){
            $menuItem = new MenuItem;
            $menuItem->name = $breakfasts[$i];
            $menuItem->meal_type_id = 1;
            $number = $faker->numberBetween($min = 10, $max = 25);
            $menuItem->description = $faker->sentence($nbWords = $number, $variableNbWords = false);
            $menuItem->save();
        }
        
        $snacks = ["pretzels", "chips", "carrot sticks", "celery", 'cheese wedge', 'oreo', 'granola', 'crackers', 'peanuts',
                  'trail mix', 'handful of crumbs', 'kraft mac and cheese cup', 'string cheese', 'hummus', 'jerky'];
        for($i = 0; $i<count($snacks);$i++){
            $menuItem = new MenuItem;
            $menuItem->name = $snacks[$i];
            $menuItem->meal_type_id = 2;
            $number = $faker->numberBetween($min = 10, $max = 25);
            $menuItem->description = $faker->sentence($nbWords = $number, $variableNbWords = false);
            $menuItem->save();
        }
        
        $lunches = [
            'blt',
            "roast salmon",
            "acai bowl",
            "italian hero",
            "sushi",
            "Panzanella",
            "marinated lentils with broccolini and feta",
            "Greek salad",
            "Pan-roasted chicken thighs",
            "Five-ingredient soboro beef",
            "taco bowl",
            "microwaved Enchiladas",
            "Cacio e Pepe",
            "Pork and bean pasta",
            "japchae",
            "Sausage, greens, and beans pasta.",
            "Cold noodle salads",
            "Stir-fried udon with pork and vegetables",
            "One-pot baked pasta with sausage and broccoli rabe",
            "Spaghetti and meatballs",
            "Shredded chicken salad",
            "BBQ chicken pizza",
            "Mexican-style pizza",
            "Fried rice with chopped up chicken.",
            "Summer rolls with chicken",
            "Skillet chicken pot pie",
            "Chicken and dumplings",
            "Chicken and black bean tacos",
            "beef chili",
            "chicken chorizo chili",
            "Lentil soup",
            "Celery soup",
            "salmorejo",
            "Instant miso soup",
            "Green minestrone with pesto",
            "Tortilla soup",
            "Borscht",
            "Chicken stew",
            "frittata",
            "Hard-boiled eggs",
            "Salmon niçoise salad",
            "overnight oats",
            "a sad lunchable",
            "Tupperware of cashews, an apple, and yogurt because you forgot to grocery shop",
            "A bag of Chex Mix and a banana",
            "microwave nachos",
            "Tortilla with canned refried beans you pry open at your desk",
            "Microwaveable packet of rice",
            "Lettuce wrapped around lunch meat, dipped in hummus",
            "An old doughnut sitting in the office shared kitchen",
            "A can of soup that you try to make better with a drizzle of olive oil",
            "Granola bar",
            "wilted salad",
            "Steamable frozen bag of vegetables with a Parmesan + red pepper flake sprinkle",
            "Triscuits and a block of cheddar"];
        for($i = 0; $i<count($lunches);$i++){
            $menuItem = new MenuItem;
            $menuItem->name = $lunches[$i];
            $menuItem->meal_type_id = 3;
            $number = $faker->numberBetween($min = 10, $max = 25);
            $menuItem->description = $faker->sentence($nbWords = $number, $variableNbWords = false);
            $menuItem->save();
        }
        
        $appetizers = [
            "Bacon-Pimiento Guacamole",
            "Warm Spinach-Sweet Onion Dip with Country Ham",
            "Crispy Baked Chicken Wings",
            "Georgia-Style Boiled Peanuts",
            "Smoky Black-Eyed Pea Hummus",
            "Easy Buffalo Chicken Dip",
            "Ham-and-Cheese Sliders",
            "Warm Cheese-and-Spicy Pecan Dip",
            "Sweet-and-Salty Snack Mix",
            "Baked BLT Dip",
            "Set Out These Apps, Then Watch Them Disappear",
            "Stuffed Endive with Herbed Goat Cheese",
            "Sweet Potato and Chorizo Sausage Bites",
            "Quick Pickled Brussels Sprouts",
            "Yeast Rolls",
            "Mini Black Bean and Cheese Enchiladas",
            "Baby Hasselback Potatoes with Blue Cheese",
            "Cornmeal Popovers",
            "Baked Brie Bites",
            "Party Poppers",
            "Cured Salmon with Dill-Horseradish Cream",
            "Spinach-and-Vidalia Dip",
            "Deviled Potatoes",
            "Crawfish Dip",
            "Tex-Mex Deviled Eggs",
            "Cheese Snappy Wafers",
            "Party-Perfect Meatballs",
            "Smoked Trout Crostini with Radishes and Dill",
            "Lump Crab Mornay",
            "Cocktail Meatballs",
            "Blue Cheese-Red Currant Cheese Ball",
            "Roasted Fennel-and-Prosciutto Flatbread",
            "Feta-Olive-Fresh Herb Cheese Ball",
            "Grapefruit-Beet-Goat Cheese Flatbread",
            "Tiny Tomato Tarts",
            "Inside-Out Hot Brown Bites",
            "Creamy Shrimp Dip with Crispy Wonton Chips",
            "Chicken Liver Mousse Crostini with Pepper",
            "Mushroom Puffs",
            "Warm Turnip Green Dip",
            "Petite Sweet Potato Biscuits with Pulled",
            "Southern-Style Smørrebrød",
            "Cheddar-Horseradish-Walnut Cheese Ball",
            "Blue Cheese Crostini with Balsamic-Roasted",
            "Slow-Cooker Beef Nachos",
            "Buttermilk-Ricotta Cheese Dip",
            "Buttery Toasted Pecans",
            "Spiced Butternut-Pumpkin Soup",
            "Cheese Dreams Recipe",
            "Mini Corn Cakes with Smoked Salmon and Dill",
            "Asparagus with Curry Dip",
            "Chicks in a Blanket",
            "Asparagus-Blue Cheese Canapés",
            "Roasted Shallot Dip",
            "Rosemary Salt-and-Vinegar Chips",
            "Pumpkin-Carrot Soup Shooters With Coconut",
            "Warm Kale-and-Asiago Dip",
            "Black-Eyed Pea Pâté",
            "Pimiento Cheese Gougères",
            "Pepper Jelly Palmiers",
            "Cranberry-Goat Cheese Canapés",
            "Contemporary Shrimp Cocktail",
            "Muffuletta Deviled Eggs",
            "Rosemary Focaccia Bread",
            "Turnip Green Pesto",
            "Cornmeal Tarts with Ricotta Pimiento Cheese",
            "Bacon-Grits Fritters",
            "Cranberry-Pecan Chutney",
            "Chicken Liver Pâté",
            "Green Goddess Dipping Sauce",
            "Caramelized Onion-and-Apple Tassies",
            "Salt-and-Pepper Oven Fries",
            "Spiced Pecans",
            "Broccoli Salad Dip",
            "Caramelized Onion and Goat Cheese Bread",
            "Buffalo Chicken Pot Stickers",
            "Orange-Basil Yogurt Dip",
            "Sweet-&#39;n&#39;-Salty Honey Cheese Spread",
            "Pickled Tiny Tomatoes",
            "Buttery Garlic Shrimp",
            "Stuffed Mushrooms with Pecans",
            "Pimiento-Stuffed Summer Squash",
            "Guacamole-Goat Cheese Toasts",
            "Brown Sugar Fruit Dip",
            "Baked Brie with Jezebel Peaches",
            "Shrimp Mojo de Ajo",
            "Blackberry-Brie Pizzettas",
            "Apple Flatbread",
            "Apple Butter-and-Cheddar Puffs",
            "Butternut-Goat Cheese Mushrooms",
            "Spicy-Sweet Pecans",
            "Sweet Potato Squares With Lemon-Garlic",
            "Jalapeño Cheese Straws",
            "Baked Goat Cheese Dip",
            "Tomato-Rosemary Tart",
            "Blue Cheese-Bacon Dip Appetizer",
            "Mustard-Dill Tortellini Salad Skewers",
            "Marinated Mozzarella",
            "Tuna-Apple Mini Melts",
            "Marinated Shrimp-and-Artichokes",
            "Assemble-Your-Own Barbecue Stacks",
            "Curried Shrimp Tarts",
            "Baked Fig Crostini",
            "Caesar Salad Bites",
            "Cheese Ring with Strawberry Preserves",
            "Chilled Sweet Pea Soup with Mint and",
            "Classic Pimiento Cheese",
            "Texas Cranberry Chutney",
            "Meatball Sliders with Tomato Sauce",
            "Slow-Cooker Beef Sliders with Pickled"
        ];
        for($i = 0; $i<count($appetizers);$i++){
            $menuItem = new MenuItem;
            $menuItem->name = $appetizers[$i];
            $menuItem->meal_type_id = 4;
            $number = $faker->numberBetween($min = 10, $max = 25);
            $menuItem->description = $faker->sentence($nbWords = $number, $variableNbWords = false);
            $menuItem->save();
        }
        
        $dinners = [
            "gumbo", "north carolina style barbecue", "texas style barbecue",
            "kansas city-style barbecue", "memphis-style barbecue", "santa maria-style barbecue", 
            "chicago-style pizza", "new york-style pizza", "detroit-style pizza", "tacos", "stir fry",
            "burritos", "fajitas", "burgers", "hamburger", "hotdog", "meatballs and rice", "sloppy joes",
            "bowtie pasta & veggies", "chicken and rice", "pulled bbq chicken", "pot roast", 
            "salsa chicken", "ribs", "french dip sandwiches", "tortellini soup", "rice and beans",
            "loaded potatoes", "jambalaya", "homemade pizza", "twice-baked potatoes", 
            "chicken pot pie", "homemade corn dogs", "calzones", "chicken cordon bleu", 
            "french bread pizza", "enchiladas", "egg rolls", "stuffed green peppers", 
            "chicken parmesan", "chicken curry", "fried chicken", "breaded chicken", 
            "chicken and broccoli", "orange chicken", "cilantro lime chicken", "lemon chicken",
            "chicken wings", "chicken nuggets", "pork chops", "chimichangas", "meat loaf", 
            "meatball subs", "stuffed pork chops", "beef & broccoli", "ham & potatoes", 
            "beef/pork tenderloin", "beef stroganoff", "steak", "herb crusted salmon", "crab cakes",
            "fish n' chips", "homemade fish sticks", "blackened fish tacos", "baked tilapia",
            "oven fried fish", "salmon with avocado", "salmon patties", "pan fried cod", 
            "mac n' cheese", "lasagna/lasagna rolls", "baked ziti", "fettuccine alfredo",
            "stuffed pasta shells", "manicotti", "spaghetti & meatballs", "pesto pasta", 
            "tortellini", "pad thai", "taco soup", "minestrone", "chicken noodle soup", 
            "potato soup", "white chicken chili", "clam chowder", "tomato bisque", "tortilla soup",
            "cheeseburger soup", "french onion soup", "black bean salad", "bbq chicken sandwich",
            "grilled cheese", "baked italian sandwich", "blt's", "egg roll bowl", 
            "grilled chicken salad", "cafe rio pork salad", "club salad", "nuts & berries salad",
            "kebabs", "grilled foil packets", "teriyaki chicken", "honey chicken", "hawaiian pork chops",
            "grilled pizza", "skirt steak", "sausage", "shrimp", "vegetable soup", "shepherd's pie", 
            "goulash", "quiche", "quesadillas", "nachos", "taco salad", "paninis", "stromboli", "casserole"
        ];
        for($i = 0; $i<count($dinners);$i++){
            $menuItem = new MenuItem;
            $menuItem->name = $dinners[$i];
            $menuItem->meal_type_id = 5;
            $number = $faker->numberBetween($min = 10, $max = 25);
            $menuItem->description = $faker->sentence($nbWords = $number, $variableNbWords = false);
            $menuItem->save();
        }
        
        $sides = [
            "Asparagus",
            "Baked beans",
            "Baked potatoes",
            "Broccoli",
            "Cabbage",
            "Cauliflower",
            "Coleslaw",
            "rolls",
            "French fries",
            "Green beans",
            "Braised Greens",
            "Macaroni salad",
            "Macaroni and cheese",
            "Mashed potatoes",
            "Pasta salad",
            "Potato salad",
            "Salad",
            "Sautéed mushrooms",
            "Squash",
            'toast',
            'tofu',
            "tempeh"
        ];
        for($i = 0; $i<count($sides);$i++){
            $menuItem = new MenuItem;
            $menuItem->name = $sides[$i];
            $menuItem->meal_type_id = 6;
            $number = $faker->numberBetween($min = 10, $max = 25);
            $menuItem->description = $faker->sentence($nbWords = $number, $variableNbWords = false);
            $menuItem->save();
        }
        
        $desserts = [
            "Allahabadi cake",
            "Allerheiligenstriezel",
            "Amandine",
            "Angel cake",
            "Angel food cake",
            "Apple cake",
            "Arany galuska",
            "Babka",
            "Banbury cake",
            "Bánh",
            "Bánh bò",
            "Bánh chuối",
            "Bánh da lợn",
            "Bánh khoai mì",
            "Bánh tét",
            "Battenberg cake",
            "Baumkuchen",
            "Berlingozzo",
            "Better than sex cake",
            "Bika Ambon",
            "Birthday cake",
            "Bizcocho",
            "Black bun",
            "Black Forest cake",
            "Blackout cake",
            "Blondie",
            "Bolo Rei",
            "Brownie",
            "Buccellato",
            "Buckwheat gateau",
            "Bulla cake",
            "Bundt cake",
            "Butter cake",
            "Butterkuchen",
            "Cake balls",
            "Cake pop",
            "Caraway seed cake",
            "Carrot cake",
            "Cassata",
            "Castella",
            "Chantilly cake",
            "Charlotte",
            "Cheesecake",
            "Chelsea bun",
            "Chiffon cake",
            "Chocolate cake",
            "Chokladboll",
            "Chongyang Cake",
            "Chorley cake",
            "Christmas cake",
            "Coconut cake",
            "Coffee cake",
            "Cupcake",
            "Cupcone",
            "Dacquoise",
            "Depression cake",
            "Devil's food cake",
            "Dirt cake",
            "Doberge cake",
            "Dobos torte",
            "Donauwelle",
            "Dundee cake",
            "Eccles cake",
            "Eggies",
            "Eierschecke",
            "Esterházy torte",
            "Fat rascal",
            "Financier",
            "Flourless chocolate cake",
            "Foam cake",
            "Frankfurter Kranz",
            "Friand",
            "Frog cake",
            "Fruitcake",
            "Funing big cake",
            "Garash cake",
            "Genoa cake",
            "Genoise",
            "German chocolate cake",
            "Gingerbread",
            "Gingerbread house",
            "Gooey butter cake",
            "Groom's cake",
            "Gugelhupf",
            "Happy Cake",
            "Heavy cake",
            "Herman cake",
            "Hot milk cake",
            "Hummingbird cake",
            "Ice cream cake",
            "Imagawayaki",
            "Jaffa Cakes",
            "Joffre cake",
            "Kalathappam",
            "Kek Lapis Sarawak",
            "Kentucky jam cake",
            "Kyiv cake",
            "King cake",
            "Kladdkaka",
            "Kornigou",
            "Kouign-amann",
            "Kransekake",
            "Kuchen",
            "Kue cubit",
            "Ladyfinger",
            "Lamington",
            "Lane cake",
            "Lardy cake",
            "Layer cake",
            "Lekach",
            "Linzer torte",
            "Madeira cake",
            "Madeleine",
            "Malt loaf",
            "Marble cake",
            "Mazurek",
            "Međimurska gibanica",
            "Molten chocolate cake",
            "Ontbijtkoek",
            "Pain d'épices",
            "Pandan cake",
            "Panforte",
            "Panettone",
            "Panpepato",
            "Parkin",
            "Parrozzo",
            "Pastiera",
            "Petit four",
            "Pinca",
            "Ploatz",
            "Pound cake",
            "Prekmurska gibanica",
            "Princess cake",
            "Prinzregententorte",
            "Punschkrapfen",
            "Put chai ko",
            "Red bean cake",
            "Red velvet cake",
            "Rigó Jancsi",
            "Rock cake",
            "Rosca de reyes",
            "Rum baba",
            "Rum cake",
            "Ruske kape",
            "Sachertorte",
            "Šakotis",
            "Šampita",
            "Sesame seed cake",
            "Sfouf",
            "Sheet cake",
            "Simnel cake",
            "Snack cake",
            "Sno Balls",
            "Song gao",
            "Spanische Windtorte",
            "Spekkoek",
            "Spice cake",
            "Sponge cake",
            "St. Honoré cake",
            "Stack cake",
            "Stollen",
            "Streuselkuchen",
            "Swiss roll",
            "Tahinopita",
            "Taiyaki",
            "Tarta de Santiago",
            "Tea loaf",
            "Teacake",
            "Tin roof pie",
            "Tipsy cake",
            "Tiramisu",
            "Torta alla Monferrina",
            "Torta caprese",
            "Torta de nata",
            "Torta Maria Luisa",
            "Torta Tre Monti",
            "Torte",
            "Tottenham cake",
            "Tres leches cake",
            "Tula pryanik",
            "Tunis cake",
            "Tunnock's teacake",
            "Upside-down cake",
            "Wacky cake",
            "Wafer",
            "Waffle",
            "Wedding cake",
            "Welsh cake",
            "White sugar sponge cake",
            "Wine cake",
            "Yule log",
            "Zuger Kirschtorte",
            "Zwetschgenkuchen",
            "Ammonia cookie",
            "Bizcochito",
            "Black and white cookie",
            "Butter cookie",
            "Butter pecan",
            "Canestrelli",
            "Caycay",
            "Chocolate chip cookie",
            "Christmas cookies",
            "Colaz",
            "Cookie bouquet",
            "Cookie dough",
            "Cookie salad",
            "Corn cookie",
            "Coyotas",
            "Fattigmann",
            "Finikia",
            "Fortune cookie",
            "Gingerbread cookie",
            "Ginger nut",
            "Guyuria",
            "Hallongrotta",
            "Jodenkoek",
            "Jumble",
            "Kichel",
            "Kleicha",
            "Koloocheh and Masgati",
            "Krumkake",
            "Kuih semperit",
            "Macaron",
            "Macaroon",
            "Maple leaf cream cookies",
            "Moravian spice cookies",
            "Mustacciuoli",
            "Nanaimo bar",
            "Nocciolini di Canzo",
            "Oatmeal raisin cookie",
            "Panellets",
            "Peanut butter cookie",
            "Pignolo",
            "Pizzelle",
            "Polvorón",
            "Qurabiya",
            "Rainbow cookie",
            "Reshteh khoshkar",
            "Rock cake",
            "Rose cookies",
            "Rosette",
            "Roskette",
            "Russian tea cake",
            "Sandbakelse",
            "Silvana",
            "Snickerdoodle",
            "Sohan",
            "Stroopwafel",
            "Sugar cookie",
            "Teiglach",
            "Thin Mints",
            "Tuile",
            "Tuticorin macaroon",
            "Whoopie pie",
            "Banana pudding",
            "Bavarian cream",
            "Bean pie",
            "Berliner",
            "Bienenstich",
            "Bob Andy pie",
            "Boston cream doughnut",
            "Boston cream pie",
            "Bougatsa",
            "Bread and butter pudding",
            "Buttermilk pie",
            "Charlotte",
            "Cheesecake",
            "Chiboust cream",
            "Clafoutis",
            "Coconut custard",
            "Coconut jam",
            "Cream pie",
            "Crème anglaise",
            "Crème brûlée",
            "Crème caramel",
            "Custard pie",
            "Custard tart",
            "Éclair",
            "Egg tart",
            "Far Breton",
            "Flanby",
            "Flapper pie",
            "Floating island",
            "Flourless chocolate cake",
            "Frangipane",
            "French toast",
            "Frozen custard",
            "Galaktoboureko",
            "Kissel",
            "Kogel mogel",
            "Kremna rezina",
            "Kremówka",
            "Krempita",
            "Krofne",
            "Malvern pudding",
            "Manchester tart",
            "Mató de Pedralbes",
            "Melktert",
            "Miguelitos",
            "Mille-feuille",
            "Nanaimo bar",
            "Natillas",
            "Neenish tart",
            "Norman Tart",
            "Ozark pudding",
            "Pączki",
            "Pastel de nata",
            "Pio Quinto",
            "Pot de crème",
            "Profiterole",
            "Pudding",
            "Pumpkin pie",
            "Queen of Puddings",
            "Quindim",
            "Rožata",
            "Salzburger Nockerl",
            "Skolebrød",
            "Soufflé",
            "ice cream",
            "St. Honoré cake",
            "Sweet potato pie",
            "Tarte à la Bouillie",
            "Tiramisu"
        ];
        for($i = 0; $i<count($desserts);$i++){
            $menuItem = new MenuItem;
            $menuItem->name = $desserts[$i];
            $menuItem->meal_type_id = 7;
            $number = $faker->numberBetween($min = 10, $max = 25);
            $menuItem->description = $faker->sentence($nbWords = $number, $variableNbWords = false);
            $menuItem->save();
        }
        
        $drinks = [
            "sprite",
            'pepsi', 
            'coca cola',
            'seltzer',
            'water',
            'tea',
            'coffee',
            'soylent', 
            'milk',
            'almond milk', 
            'oat milk', 
            'mountain dew', 
            'beer', 
            "wine", 
            "hot chocolate", 
            "lemonade",  
            "wine", 
            "red bull",
            "horchata",
            "ale 8", 
            "kool aid", 
            "shirley temple",
            'orange juice',
            'spirits'
        ];
        for($i = 0; $i<count($drinks);$i++){
            $menuItem = new MenuItem;
            $menuItem->name = $drinks[$i];
            $menuItem->meal_type_id = 8;
            $number = $faker->numberBetween($min = 10, $max = 25);
            $menuItem->description = $faker->sentence($nbWords = $number, $variableNbWords = false);
            $menuItem->save();
        }
        
        $sauces = [
            "ketchup",
            "honey",
            "mustard",
            'lemon juice',
            "Demi glace",
            "Gravy",
            "Hollandaise",
            "Mayonnaise",
            "garlic aioli",
            "Tartar sauce",
            "siracha",
            "balsamic",
            "vinegar",
            "maple syrup",
            'hot sauce',
            'ranch',
            'soy sauce',
            "Avgolemono",
            "Barbecue sauce",
            "Cocktail sauce",
            "Coulis",
            "Mint chutney",
            "Pan sauce",
            "Romesco",
            "salsa roja",
            "Sofrito",
            "Sour cream",
            "Steak sauce",
            "Tomato sauce",
            "Vinaigrette",
            "Wine sauce",
            "Worcestershire sauce"
        ];
        for($i = 0; $i<count($sauces);$i++){
            $menuItem = new MenuItem;
            $menuItem->name = $sauces[$i];
            $menuItem->meal_type_id = 9;
            $number = $faker->numberBetween($min = 10, $max = 25);
            $menuItem->description = $faker->sentence($nbWords = $number, $variableNbWords = false);
            $menuItem->save();
        }
    }
}
